parametrization_name: layers
parametrization_class: diffuser

parametrization_hyperparams:
  matrix_size: [3, 3]
  layers_num: 1
  tau: 20e-3
  delta: 10e-3
  asymmetry_factor: 0.8

optimization_hyperparams:
  seed: 42
  iterations: 200
  bandwidth: 1000
  number_of_frequencies: 3
  general_frequency: 5750
  frequencies: []
  scattering_angle: [180, ]

scattering_hyperparams:
  theta: 180
  eta: 0
  phi: 90

object_hyperparams:
  type: ssr
  dist_from_obj_to_surf: 6e-2
  size_ratio: 1.0

