parametrization_name: layers
parametrization_class: diffuser

parametrization_hyperparams:
  matrix_size: [3, 3]
  layers_num: 1
  tau: 20e-3
  delta: 10e-3
  asymmetry_factor: 0.8

optimization_hyperparams:
  seed: 42
  iterations: 300
  bandwidth: 1000
  number_of_frequencies: 3
  general_frequency: 5500
  frequencies: []
  scattering_angle: [180, ]

scattering_hyperparams:
  theta: 180
  eta: 0
  phi: 90

object_hyperparams:
  type: sphere
  dist_from_obj_to_surf: 16e-2
  radius: 0.025
  config: 
    phi_segments: 9
    theta_segments: 9
