parametrization_name: layers
parametrization_class: diffuser

parametrization_hyperparams:
  matrix_size: [3, 3]
  layers_num: 1
  tau: 20e-3
  delta: 10e-3
  asymmetry_factor: 0.8

optimization_hyperparams:
  seed: 45
  iterations: 150
  bandwidth: 1200
  number_of_frequencies: 15
  general_frequency: 5500
  frequencies: []
  scattering_angle: [180, ]

scattering_hyperparams:
  theta: 180
  eta: 0
  phi: 90

object_hyperparams:
  type: srr
  dist_from_obj_to_surf: 4e-2
  size_ratio: 0.0
  orientation: [0,0,0]

