parametrization_name: layers
parametrization_class: diffuser

parametrization_hyperparams:
  matrix_size: [3, 3]
  layers_num: 1
  tau: 20e-3
  delta: 10e-3
  asymmetry_factor: 0.9

optimization_hyperparams:
  seed: 41
  iterations: 10
  bandwidth: 1200
  number_of_frequencies: 15
  general_frequency: 5900
  frequencies: []
  scattering_angle: [180, ]
  scattering_theta_angle: 180

scattering_hyperparams:
  theta: 180
  eta: 0
  phi: 90

object_hyperparams:
  type: ssrr
  dist_from_obj_to_surf: 6e-2
  size_ratio: 1.0
  orientation: [0,0,0]
  wire_radius: 0.1e-3

