#parametrization_name: layers
#parametrization_class: diffuser
#
#parametrization_hyperparams:
#  matrix_size: [3, 3]
#  layers_num: 1
#  tau: 20e-3
#  delta: 10e-3
#  asymmetry_factor: 0.8

parametrization_name: sphere
parametrization_class: diffuser

parametrization_hyperparams:
  matrix_size: [3, 3, 1]
  tau_x: 40e-3
  tau_y: 40e-3
  tau_z: 40e-3

optimization_hyperparams:
  seed: 42
  iterations: 1
  bandwidth: 1000
  number_of_frequencies: 1
  general_frequency: 4800
  frequencies: []
  scattering_angle: [180, ]

scattering_hyperparams:
  theta: 180
  eta: 0
  phi: 90

object_hyperparams:
  type: sphere
  dist_from_obj_to_surf: 9e-2
#  wire_radius: 0.5 * 1e-4
#  radius: 0.025
  size_ratio: 0.0
  orientation: [0,0,0]
  config: 
    phi_segments: 4
    theta_segments: 4
